### ISSUE TITLE
Consider a different license

### ISSUE THREAD

**Issue by ElDeveloper** [daleroberts/hdmedians#1]
We are considering using this package in [scikit-bio](http://scikit-bio.org) (a BSD 3-clause licensed package), but the GPL license would require us to change our package to a GPL-like license. Can you consider double-licensing hdmedians, or grant us permission to use this without the need to change our license?

**Comment by alfredo-ama** [comment]
Hi Dale, 

I'd like to second the request for a double-licensed release if at all possible. We'd like to use this package for our [CEOS/Data Cube released material](https://github.com/ceos-seo), but due to some NASA release process restrictions we aren't able to use anything licensed with GPL.

**Comment by daleroberts** [comment]
Hi, sorry I didn't have notifications enabled on this repo. I wasn't expecting people to find it at this point.

My worries, based on what you both are saying, are that:
- I'll lose attribution on this work.
- This is still under development and if you this copy/paste code into your repo/project you might miss bug fixes and enhanced functionality compared to just making this a dependency.
- This is a small part of a much larger project under (private) development that will be released to the public in the future when research papers are accepted by journals.

Any comments on this? I'm happy to consider a BSD licence but just trying to understand the pros/cons.

**Comment by alfredo-ama** [comment]
Hi Dale,

I was pointed to this repository by Norman Mueller/Brian Killough to make use of it in a few of our Data Cube open source projects. I'm really just looking to be able to list this as a dependency/requirement for our project - pretty much any other license would work for us. We won't be copying code, rather it'll be an entry in our requirements.txt/included in the docs to either pip install the package or clone the repository. As far as losing attribution to the work, I'm not too knowledgeable on how that works. Since we're only looking to list it as a dependency, does that alleviate some of your worries?

**Comment by daleroberts** [comment]
Thanks @alfredo-ama I was getting worried.

@ElDeveloper how are you intending on using it?

**Comment by ElDeveloper** [comment]
@daleroberts thanks for your reply 👍.

Our intended use-case is pretty much the same as @alfredo-ama's, we are hoping to add hdmedians to our `setup.py`, you wouldn't lose attribution as we would be installing from the package you uploaded to pip.

GPL is rather restrictive on this regard, because although our project is released under the BSD license, including a GPL dependency forces the project to go GPL `**`.  Hence why having this released under a different license would be handy. 😃 

------------

`**` Disclaimer: I'm not a lawyer, but this is my understanding from googling around.

**Comment by daleroberts** [comment]
I changed the licence to Apache.

**Comment by ElDeveloper** [comment]
@daleroberts, that is phenomenal!! Thanks for doing this.
